name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_push:
    if: "!contains(github.event.head_commit.message, '[no-build]')"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /tmp/*
          sudo rm -rf /opt/hostedtoolcache
          sudo apt-get clean
          docker system prune -af
          echo "Disk space after cleanup:"
          df -h

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/bpjs-ai/genefaceplusplus
          tags: latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push genfaceplus image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.genface
          push: true
          platforms: linux/amd64
          tags: ghcr.io/bpjs-ai/genefaceplusplus:latest
